stages:
  - test

services:
  - docker:dind

variables:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: merchshop

before_script:
  - docker-compose up -d
  - while ! docker-compose exec db pg_isready -U postgres -d merchshop; do sleep 1; done

api_tests:
  stage: test
  image: golang:1.21
  script:
    - cd test/api_test
    - go test -v -race ./...

service_tests:
  stage: test
  image: golang:1.21
  script:
    - cd test/service_test
    - go test -v -race ./...

after_script:
  - docker-compose down