name: Run Tests

on:
  push:
    branches: [develop, feature/*]
  pull_request:
    branches: [main]

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: merchshop
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      
      - name: Wait for PostgreSQL
        run: |
          for i in {1..10}; do
            if pg_isready -h localhost -U postgres -d merchshop; then
              break
            fi
            sleep 2
          done
      
      - name: Run API tests
        run: |
          cd test/api_test
          go test -v -race ./...
      
      - name: Run Storage tests
        run: |
          cd test/storage_test
          go test -v -race ./...